const books =[
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Faceless", "author":"Ama", "publication": "12/03/2021", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"},
    {"title": "Things fall apart", "author":"Chinedu", "publication": "12/03/2022", "type":"fiction"}
]
 module.exports =books